name: Run Driving Test Bot

on:
  schedule:
    # Runs approximately every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Max time for the job to run

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # You can choose 3.8, 3.9, 3.10, 3.11 etc.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers & OS dependencies
        run: python -m playwright install --with-deps chromium # Only Chromium needed for this script

      - name: Run the bot script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          USER_DL_NUMBER: ${{ secrets.USER_DL_NUMBER }}
          USER_CONTACT_NAME: ${{ secrets.USER_CONTACT_NAME }}
          USER_CONTACT_PHONE: ${{ secrets.USER_CONTACT_PHONE }}
        run: python driving_bot.py # Make sure this matches your Python script's filename
