name: Run Driving Test Bot

on:
  schedule:
    # Runs approximately every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  run-bot: # You can name this job whatever you like
    runs-on: ubuntu-latest
    timeout-minutes: 10 # Maximum time the job is allowed to run (e.g., 10-15 minutes)

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' # Or your preferred Python version (e.g., 3.10, 3.11)

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers & OS dependencies
        run: python -m playwright install --with-deps chromium # Installs only Chromium and its OS dependencies

      - name: Run the bot script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          USER_DL_NUMBER: ${{ secrets.USER_DL_NUMBER }}
          USER_CONTACT_NAME: ${{ secrets.USER_CONTACT_NAME }}
          USER_CONTACT_PHONE: ${{ secrets.USER_CONTACT_PHONE }}
        run: python driving_bot.py # Make sure this matches your Python script's filename
